### ISSUE TITLE
Slack message box disappears

### ISSUE THREAD

**Issue by yochananmarqos** [PeterCxy/Lolistat#8]
With both Lolistat 1.0 & 1.0.1, Slack's message box at the bottom disappears. 

With Lolistat enabled: 
![2015-02-25 15 07 52](https://cloud.githubusercontent.com/assets/5437803/6381673/51fc412c-bd00-11e4-9271-70457d4e1fab.png)

With Lolistat disabled (ignore the extra button on the nav bar, that's unrelated):
![2015-02-25 15 12 52](https://cloud.githubusercontent.com/assets/5437803/6381742/d26cd376-bd00-11e4-87c4-c8b87e805b3b.png)

**Comment by PeterCxy** [comment]
Looks a little strange. I will try slack later.

**Comment by PeterCxy** [comment]
I assume that this has been fixed in the latest release. Could you upgrade and confirm it? I do not have a Slack account.

**Comment by yochananmarqos** [comment]
No, it did not resolve the issue. I'll contact Slack support see what they have to say. Maybe they have a test account you can use.

**Comment by PeterCxy** [comment]
I assumed that the disappearing of the box was caused by expanding behind the navigation bar. But now it seems that the reason is more than that. I'll try to get a Slack team account recently and try to fix this. Anyway it is such a strange issue -_-

**Comment by yochananmarqos** [comment]
I forgot you can create a Slack team for free, so that should be no issue.

Slack support said to let you know that the sendbar is set to android:layout_alignParentBottom="true", and that that might help you figure out what's happening.

**Comment by PeterCxy** [comment]
still no idea about this. It seems like a bug with the sliding menu library that Slack uses, but I cannot figure out why it happens.

**Comment by yochananmarqos** [comment]
Blacklisting Slack solves the issue in r2. Thanks!
